### ISSUE TITLE
Silly request

### ISSUE THREAD

**Issue by mizeboud** [bvreede/horizon-spotting#6]
**Is your feature request related to a problem? Please describe.**
The answer in the markdown cell is independent of the output of the kernel. Can this be dependent? 

**Describe the solution you'd like**
Include a variable in markdown cell

**Describe alternatives you've considered**

**Additional context**

**Comment by bvreede** [comment]
Thanks for the suggestion! This issue is similar to an issue already described. It is being tackled right now by @jhidding and @samnooij
